---
output: html_document
---

```{r setup, include=FALSE}

library(dplyr)

# find latest
filenames <- dir("data", full.names = TRUE)

most_recent <- basename(filenames) %>% lubridate::ymd(.) %>% which.max()

bab_data <- readr::read_csv(filenames[most_recent],
                            col_types = "Dccccccccc")


Sys.setlocale("LC_ALL","fr_CA")

pad2 <- function(time_fun) function(d) formatC(time_fun(d), width = 2, format = "d", flag = "0")

# make the presenter a link
```

```{r echo = FALSE}
bab_data %>%
  filter(Date >= Sys.Date()) %>%
  mutate(`Présentateur / Responsable` =
           if_else(is.na(Lien_Presentateur), 
                   true = `Présentateur / Responsable`,
                   false = paste0("<a href='",Lien_Presentateur,"'>",
                                  `Présentateur / Responsable`,
                                  "</a>"))) %>%
  select(-Lien_Presentateur) %>%
  mutate(Détails =
           if_else(is.na(Lien_Details), 
                   true = Détails,
                   false = paste0("<a href='",Lien_Details,"'>",
                                  Détails,
                                  "</a>"))) %>% 
  select(-Lien_Details) %>%
  # format times
  mutate(
    # Date = paste(lubridate::day(Date), lubridate::month(Date, label = TRUE)),
    Début = sub(":00$", "", Début),
    Fin = sub(":00$", "", Fin)
  ) %>% 
  arrange(Date) %>% 
  DT::datatable(escape = FALSE, rownames = FALSE)
```
